name: Publish to GitHub Pages
on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clone
        uses: actions/checkout@v2
        with:
          repository: MarvDan/antora-docs-evaluation
          ref: develop
          submodules: true          
                    
      - name: Run Antora
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: docs/antora-playbook.yml
          
      - name: Artifact build upload
        uses: actions/upload-artifact@v2
        with: 
          name: my-artifact
          path: docs/build
